services:

  frontend:
    build:
      context: ./frontend
      args:
        API_URL: http://localhost:8080
    ports:
      - "3000:80"
    labels:
      traefik.enable: "true"
      traefik.http.routers.frontend.rule: "Host(`frontend.localhost`)"
      traefik.http.services.frontend.loadbalancer.server.port: "80"

  backend:
    build:
      context: ./backend
    ports:
      - "8080:8080"
    labels:
      traefik.enable: "false"
  
  traefik:
    image: traefik:v2.5
    command:
      - "--api.insecure=true"
      - "--providers.docker=true"
      - "--entrypoints.web.address=:80"
      - "--entrypoints.websecure.address=:443"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    ports:
      - "80:80"
      - "443:443"
      - "8081:8080"
    labels:
      traefik.enable: "true"
      traefik.http.routers.api.rule: "Host(`traefik.localhost`)"
      traefik.http.routers.api.service: "api@internal"
      traefik.http.routers.api.entrypoints: "web"